on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy on local server
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Stop existing container
      run: docker compose down || true

    - name: Build and run new container
      run: docker compose up -d --build

    - name: Wait for container to start
      run: sleep 5

    - name: Verify API is responding
      run: |
        STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/)
        if [ "$STATUS_CODE" -ne 200 ]; then
          echo "❌ API no respondió correctamente. Código: $STATUS_CODE"
          exit 1
        else
          echo "✅ API responde correctamente (200 OK)"
        fi

    - name: Notificar en Discord
      uses: rjstone/discord-webhook-notify@v1
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        severity: success
        text: "🚀 FastAPI desplegado y verificado correctamente en servidor local tras merge en develop."
