name: Deploy FastAPI App on Merge to Develop

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy on local server
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Stop existing container
      run: docker compose down || true

    - name: Build and run new container
      run: docker compose up -d --build

    - name: Notificar en Discord
      uses: rjstone/discord-webhook-notify@v1
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        severity: success
        text: "🚀 FastAPI desplegado en servidor local tras merge en develop."