name: Deploy FastAPI App on Merge to Develop

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy on local server
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Stop existing container
      run: docker compose down || true

    - name: Build and run new container
      run: docker compose up -d --build
      
    - name: Notify on Discord
      uses: actions-discord@v1.1.1  # Acción alternativa verificada
      with:
        discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
        discord-content: "🚀 FastAPI deployed on local server after merge to develop"  
